### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by osdnk** [tsapeta/Pastels#44]
Hi, @tsapeta 
I wish to congratulate this great app. 
However, I wish to open it locally and didn't manage. Would you mind attach readme?

**Comment by osdnk** [comment]
Hi, @tsapeta 
I really can't stand waiting for you answer as it is crucial for my new project

**Comment by Tchayen** [comment]
@tsapeta is there any ETA on the fix? It is critical for my app. Please get in touch ASAP.

**Comment by aleqsio** [comment]
Still not working

**Comment by aleqsio** [comment]
Please ETA on the fix.

**Comment by osdnk** [comment]
https://www.youtube.com/watch?v=HG7I4oniOyA
